modLoader="javafml"
loaderVersion="[${majorForgeVersion},)"
license="All rights reserved"
[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="Random Dimensions"
	#logoFile="RandomDimensionsLogo.png"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/RandomDimensions.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/random-dimensions/issues"
	displayURL="https://minecraft.curseforge.com/projects/random-dimensions"
	authors="mrp_v2"
	description='''Adds portals that take you wherever you want.'''
[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="[${majorForgeVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion}]"
    ordering="NONE"
    side="BOTH"